import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Primary Page',
  description: 'Generated by create next app manipulated by David Cruz',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head/>
      <body className={inter.className}>
        <nav>
          <h1>My Noway</h1>
        </nav>
        {children}
      </body>
    </html>
  )
}
